version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: form-fluoce-db
    environment:
      POSTGRES_USER: form-fluoce
      POSTGRES_PASSWORD: form-fluoce
      POSTGRES_DB: form-fluoce
    ports:
      - "5432:5432"
    volumes:
      - "C:/Users/ashit/OneDrive/temp/docker-volumes/DB/form-fluoce:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    container_name: form-fluoce-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "C:/Users/ashit/OneDrive/temp/docker-volumes/redis/form-fluoce:/data"
